# Most of this is inspired by the mypy primer
# See: https://github.com/hauntsaninja/mypy_primer

name: Primer / Main

on:
  push:
    branches:
      - main

jobs:
  prepare-tests-linux:
    name: prepare / ${{ matrix.python-version }} / Linux
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.10"]
    outputs:
      python-key: ${{ steps.generate-python-key.outputs.key }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.0.2
      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate partial Python venv restore key
        id: generate-python-key
        run: >-
          echo "::set-output name=key::venv-${{ env.CACHE_VERSION }}-${{
            hashFiles('setup.cfg', 'requirements_test.txt', 'requirements_test_min.txt')
          }}"
      - name: Restore Python virtual environment
        id: cache-venv
        uses: actions/cache@v3.0.2
        with:
          path: venv
          key: >-
            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
            steps.generate-python-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-venv-${{ env.CACHE_VERSION }}-
      - name: Create Python virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install -U pip setuptools wheel
          pip install -U -r requirements_test.txt
      - name: Run pytest
        run: |
          . venv/bin/activate
          pip install -e .
          pylint setup.py > output.txt
      - name: Upload output diff
        uses: actions/upload-artifact@v3
        with:
          name: primer_pylint_output
          path: output.txt
      - name: Save PR number
        run: |
          echo ${{ github.event.pull_request.number }} | tee pr_number.txt
      - name: Upload PR number
        uses: actions/upload-artifact@v2
        with:
          name: primer_pylint_output
          path: pr_number.txt
